### ISSUE TITLE
Apollo doesn't recognize players with LunarClient

### ISSUE THREAD

**Issue by Yoshiro09** [LunarClient/Apollo#104]
Heyo, I'm trying to add full support to LunarClient on my Paper Server using Apollo, but I can't seem to get it to recognize me as a LunarClient user in any way.
Ive already seen #65 and idk if the problem is still the same

I'm running:
- Paper 1.20.4 git-Paper-389 (latest)
- Apollo 1.0.6 (tried 1.0.7 too)

Method: `player.sendMessage("Is a LunarUser? " + Apollo.getPlayerManager().hasSupport(player.getUniqueId()));`
![2024-01-15_23 28 55](https://github.com/LunarClient/Apollo/assets/62937008/874a17ab-a622-4b94-b168-64c251e35c26)

**Comment by TrentinTheKid** [comment]
We pushed an update ~2 days ago which resulted in this breaking on 1.19.2 to 1.20.1, it'll be fixed later today in the next client deploy. (We're also adding checks to prevent these types of issues from being deployed again)
