### ISSUE TITLE
[1.20.1] Force Enable/Disable not working

### ISSUE THREAD

**Issue by JasmineWMCM** [LunarClient/Apollo#109]
I was wondering what was updated in the Lunar Client itself on 1.20.1; when you use the Fabric option the Apollo plugin no longer takes effect like it does on 1.20.4 Fabric. Anything change?

Server Version: 1.20.1
Plugin Version 1.0.8
![image](https://github.com/LunarClient/Apollo/assets/60033824/ef0db771-f026-41c8-8b01-38261588af23)

**Comment by TrentinTheKid** [comment]
It appears this issue is resolved in the latest Lunar Client deploy.
