### ISSUE TITLE
[Bug Report] Glow Module doesn't work on 1.8.9

### ISSUE THREAD

**Issue by soladev** [LunarClient/Apollo#111]
### Checklist before creating an issue:

- [X] I'm using the [latest version](https://github.com/LunarClient/Apollo/releases) of Apollo.
- [X] I'm using the latest version of Lunar Client. (Relaunched in the last hour)
- [X] I'm running Apollo on **ONLY** the backend server OR the proxy. **(YOU CANNOT RUN IT ON BOTH)**
- [X] I do **NOT** have both Apollo and the LEGACY API installed on the same server. **(YOU CANNOT RUN BOTH AT THE SAME TIME)**
- [X] I've gathered all screenshots, logs and appropriate information related to creating a bug report.

### Issue Description

The Glow Module, as described using the documentation, doesn't apply a glow with most colors, and for other colors it just display a black screen to the player that tries to see the glowing player. 

I've also tried compiling the bukkit-example folder and use the /glow override command and it still didn't work properly. 

### Reproduction steps

```bash
1. Compile the bukkit-example plugin
2. Use it on a 1.8.9 paper / spigot server
3. Use the /glow override <player> command
4. The screen gets black whenever the client tries to look at the glowing player
```

### Versions

1.8

### Platforms

Spigot / Bukkit

### Server Version

1.8

### Modules

Optifine

### Contact Information

```bash
Discord - soladev
```

**Comment by TrentinTheKid** [comment]
> ### Screenshots
> 
> _No response_

I can't believe you didn't include a screenshot of a fully black screen.. 😆 

Some additional context after doing further testing, it appears to be the Optifine setting 'Fast Render' being set to 'ON'. It also appears on 1.7 and 1.12 as well as 1.8, as you mentioned. Each version having it's own slightly different side-effect from that setting being enabled. We'll be looking into fixing it, thanks for the report. 👍

**Comment by soladev** [comment]
> I can't believe you didn't include a screenshot of a fully black screen.. 😆

Yeah i thought of adding it, but I guess it wouldn't have been useful to add a 1080x1920 .png of the color `#000000` :grin: 

Thanks for your answer, at least in the meantime I should be able to try the feature with Fast Render disabled

**Comment by devfugu** [comment]
My screen is also pitch black with the exception of the players outline being stuck frozen on my screen, latest lunar client on 1.7.10.

![image](https://github.com/LunarClient/Apollo/assets/52648595/5125b96e-a385-4ab5-8eac-c6644741c6a4)

**Comment by TrentinTheKid** [comment]
Hey @soladev & @devfugu,

Thanks for reporting this issue, the most recent Lunar Client (`v2.13.9-2406`) deploy has resolved this issue.
