### ISSUE TITLE
[Bug Report] Transfer module doesn’t work after player switches server on velocity 

### ISSUE THREAD

**Issue by HaeImAlan** [LunarClient/Apollo#112]
### Checklist before creating an issue:

- [X] I'm using the [latest version](https://github.com/LunarClient/Apollo/releases) of Apollo.
- [X] I'm using the latest version of Lunar Client. (Relaunched in the last hour)
- [X] I'm running Apollo on **ONLY** the backend server OR the proxy. **(YOU CANNOT RUN IT ON BOTH)**
- [X] I do **NOT** have both Apollo and the LEGACY API installed on the same server. **(YOU CANNOT RUN BOTH AT THE SAME TIME)**
- [X] I've gathered all screenshots, logs and appropriate information related to creating a bug report.

### Issue Description

If a user switches server in velocity , the transfer request does not show up on the client.

### Reproduction steps

```bash
1. Join the velocity instance
2. Switch server ( i.e from lobby to a game mode )
3. Send a transfer request
```

### Versions

1.8

### Platforms

Velocity

### Server Version

1.8

### Modules

Optifine

### Contact Information

```bash
Discord - haeimalan
```

**Comment by TrentinTheKid** [comment]
This issue was resolved in the Lunar Client update: **v2.14.8-2414**
