### ISSUE TITLE
[Bug Report] Glint doesn't work on worn armor

### ISSUE THREAD

**Issue by Usepot** [LunarClient/Apollo#164]
### Checklist before creating an issue:

- [X] I'm using the [latest version](https://github.com/LunarClient/Apollo/releases) of Apollo.
- [X] I'm using the latest version of Lunar Client. (Relaunched in the last hour)
- [X] I'm running Apollo on **ONLY** the backend server OR the proxy. **(YOU CANNOT RUN IT ON BOTH)**
- [X] I do **NOT** have both Apollo and the LEGACY API installed on the same server. **(YOU CANNOT RUN BOTH AT THE SAME TIME)**
- [x] I've gathered all screenshots, logs and appropriate information related to creating a bug report.

### Issue Description

Glint doesnt show up on worn armor only the item form as you can see in the image attached below the glint of the armor is red but the glint on the item but not on the actual armor model

### Reproduction steps

```bash
Add red glint to armor
Wear it
```

### Code Snippet (If applicable, if not write N/A)

N/A

### Versions

1.8

### Platforms

Spigot / Bukkit

### Server Version

1.8

### Modules

Optifine

### Screenshots

```bash
![image](https://github.com/user-attachments/assets/c7ab5c4b-98cc-402a-8ec2-67ca25109656)
```

### Contact Information

```bash
Discord - ambassator
```

**Comment by TrentinTheKid** [comment]
This is outside the scope of the module, this is not a standing issue. If you want to suggest its addition, do so in the [Discord](https://discord.gg/3T9Atyb6pf).
