### ISSUE TITLE
[Bug Report] Disable Miss penalty doesn't work

### ISSUE THREAD

**Issue by Usepot** [LunarClient/Apollo#165]
### Checklist before creating an issue:

- [X] I'm using the [latest version](https://github.com/LunarClient/Apollo/releases) of Apollo.
- [X] I'm using the latest version of Lunar Client. (Relaunched in the last hour)
- [X] I'm running Apollo on **ONLY** the backend server OR the proxy. **(YOU CANNOT RUN IT ON BOTH)**
- [X] I do **NOT** have both Apollo and the LEGACY API installed on the same server. **(YOU CANNOT RUN BOTH AT THE SAME TIME)**
- [X] I've gathered all screenshots, logs and appropriate information related to creating a bug report.

### Issue Description

Lunar client miss penalty doesn't work, I was trying to enable it for abt 4 hours on a custom impl when I gave up and tried using the normal one, thats when I realized that you literally cant turn it on via the official api either, and 0 servers have it on (I tested elevate, mobpvp, astralmc, sololegends, minecadia, , etc.) all servers that had it on before suddenly are broken now

### Reproduction steps

```bash
Use Legacy Combat module
Punch in air
Instantly start mining block
It doesn't mine for 0.5 seconds which means its off
```

### Code Snippet (If applicable, if not write N/A)

N/A

### Versions

1.8

### Platforms

Spigot / Bukkit

### Server Version

1.8

### Modules

Optifine

### Contact Information

```bash
Discord - Ambassator
```

**Comment by TrentinTheKid** [comment]
The method to reproduce, you've provided, won't work as you expect any longer. From my understanding the behavior was updated to match vanilla, since it gave a slight advantage. 

You'll have to detect it another way, you could try swinging at the air 10 times then a player and see if you get the penalty.
