### ISSUE TITLE
[Bug Report] Glow Module "glows" the hitbox if they are enabled

### ISSUE THREAD

**Issue by Usepot** [LunarClient/Apollo#166]
### Checklist before creating an issue:

- [X] I'm using the [latest version](https://github.com/LunarClient/Apollo/releases) of Apollo.
- [X] I'm using the latest version of Lunar Client. (Relaunched in the last hour)
- [X] I'm running Apollo on **ONLY** the backend server OR the proxy. **(YOU CANNOT RUN IT ON BOTH)**
- [X] I do **NOT** have both Apollo and the LEGACY API installed on the same server. **(YOU CANNOT RUN BOTH AT THE SAME TIME)**
- [X] I've gathered all screenshots, logs and appropriate information related to creating a bug report.

### Issue Description

Glow Module will make hitboxes glow when hitboxes are on, making it look really ugly

### Reproduction steps

```bash
Enable Glow Module
Enable Hitboxes
```

### Code Snippet (If applicable, if not write N/A)

N/A

### Versions

1.8

### Platforms

Spigot / Bukkit, BungeeCord, Velocity, Other

### Server Version

1.8

### Modules

Optifine

### Screenshots

```bash
https://lunr.pics/cHhQQ1zq.png
```

### Contact Information

```bash
Discord - Ambassator
```

**Comment by Taxalo** [comment]
Something strange seems to happen even with hitboxes off. Glowing all the player instead of the outline
![2024-09-07_18 31 31](https://github.com/user-attachments/assets/2a4e5ee1-4455-49d4-bfb9-116b625359b1)

**Comment by TrentinTheKid** [comment]
@Taxalo you're having this issue due to the 'Fast Render' setting being enabled in Optifine. If you disable it, the glow effect appears normal.
