### ISSUE TITLE
does not recognize a Lunar Client player, from another client

### ISSUE THREAD

**Issue by PhilouLeVrai** [LunarClient/Apollo#65]
![image_2023-11-30_205832879](https://github.com/LunarClient/Apollo/assets/104216753/51f3e710-03c4-45d2-82ef-bca74a472626)
![image_2023-11-30_205850723](https://github.com/LunarClient/Apollo/assets/104216753/5c25c504-339b-4051-9ed6-361219885a07)
![image_2023-11-30_205917186](https://github.com/LunarClient/Apollo/assets/104216753/5843aa12-6c95-435b-b10a-9ffb53a9075d)

**Comment by PhilouLeVrai** [comment]
Hello, i'm sure i use the 1.0.3, i use Apollo on velocity for that.

**Comment by TrentinTheKid** [comment]
Are you checking on the PreLoginEvent? Can you provide a code snippet? 

@PhilouLeVrai

**Comment by DiscowZombie** [comment]
Same issue here, `#hasSupport` is false on Velocity and the `ApolloRegisterPlayerEvent` isn't fired.

Specs:
- velocity-3.2.0-SNAPSHOT-294
- apollo-velocity-1.0.4

Code:
```java
    @Subscribe
    public void onServerPostConnectEvent(ServerPostConnectEvent event) {
        this.server.getScheduler().buildTask(this.plugin, () -> {
                    final Player pl = event.getPlayer();
                    if (pl != null) {
                        System.out.println("Has support? " + Apollo.getPlayerManager().hasSupport(pl.getUniqueId()));
                    }
                })
                .delay(1, TimeUnit.SECONDS)
                .repeat(3, TimeUnit.SECONDS)
                .schedule();
    }
```
![Capture d’écran du 2023-12-09 12-37-43](https://github.com/LunarClient/Apollo/assets/25774021/e79e26ea-0509-4a7f-9db5-9729d1244172)
![image](https://github.com/LunarClient/Apollo/assets/25774021/f4939819-6a4d-488d-8973-d1428b863ae9)

**Comment by Badbird5907** [comment]
Same issue here, using apollo-bukkit 1.0.4 on LC 1.20.2, `ApolloPlayerManager#hasSupport` returns false
![image](https://github.com/LunarClient/Apollo/assets/50347938/863ef654-2117-4b17-9dd0-477043f6b0e7)

**Comment by colinmcdonald22** [comment]
Hi all 👋 There was recently an issue where 1.20.2 specifically didn't proper send the plugin message registration. This is resolved in the latest deploy, which is still rolling out to users.

Leaving this issue open in case there's a Velocity-specific bug, but @Badbird5907's issue (and others on non-Velocity platforms) should be resolved

**Comment by colinmcdonald22** [comment]
This should now be resolved in the latest client release, please give it a try and let us know if everything works as expected @PhilouLeVrai @DiscowZombie

**Comment by DiscowZombie** [comment]
It's working, thanks! :tada:

**Comment by Yoshiro09** [comment]
Heyo, does this bug still exist? I'm using Apollo-Bukkit 1.0.6 and I can't detect Lunar users in any way in my 1.20.1 Server
