### ISSUE TITLE
When a velocity plugin does not fill the "version" field in @Plugin annotation and server statistics are activated, Apollo will not work

### ISSUE THREAD

**Issue by theFoxley** [LunarClient/Apollo#81]
The error :
![image](https://github.com/LunarClient/Apollo/assets/7950977/e8f2a5c2-d49e-4fe6-ae86-62587efc55f0)

Because in method com.lunarclient.apollo.wrapper.VelocityApolloStats#getPlugins
at the line com/lunarclient/apollo/wrapper/VelocityApolloStats.java:66

We take a null value if there is no version, maybe a non-null default value should be given or change the optionality of the field "version"

**Comment by theFoxley** [comment]
https://jd.papermc.io/velocity/3.0.0/com/velocitypowered/api/plugin/Plugin.html#version()

**Comment by vopswtf** [comment]
since minecraft version doesnt align with velocity version, could use this
https://jd.papermc.io/velocity/3.0.0/com/velocitypowered/api/proxy/ProxyServer.html#getVersion()

**Comment by theFoxley** [comment]
what but im talking about the @Plugin annotation of Velocity that allows plugin to set a version

**Comment by vopswtf** [comment]
yes, but if you look at the other stats, they get the specific Minecraft version of the server. Since velocity is a multi version proxy, proxy version should be fine

**Comment by colinmcdonald22** [comment]
This should be fixed now. No Apollo release needed, as it was ultimately an issue with the schema being enforced in our analytics backend.
