### ISSUE TITLE
Title scale is limited?

### ISSUE THREAD

**Issue by Jeyzer** [LunarClient/Apollo#86]
Using the old LC-API I was able to send multiple LCTitlePacket(s) as TitleType.SUBTITLE to create a smooth "zoom effect" by increasing the scale by a little for each packet, i tried to switch to the new API but for some reason the using of small scale isn't available, is this a wanted regression or is there any other reason this is being limited?

**Comment by TrentinTheKid** [comment]
> Using the old LC-API I was able to send multiple LCTitlePacket(s) as TitleType.SUBTITLE to create a smooth "zoom effect" by increasing the scale by a little for each packet, i tried to switch to the new API but for some reason the using of small scale isn't available, is this a wanted regression or is there any other reason this is being limited?

This was most likely an oversight, this is actually the first time I've ever heard of using titles for this reason. Would you mind sharing some example code so we can reproduce this correctly?

**Comment by Jeyzer** [comment]
Sure, here's the code i've been using:
`        Optional<ApolloPlayer> apolloPlayer = Apollo.getPlayerManager().getPlayer(killer.getUniqueId());

        if (apolloPlayer.isEmpty()) return;

        microStreak.future().thenRunAsync(() -> {
            long last = System.nanoTime();
            float current = 0.01f;

            LCTitleBuilder titleBuilder = LCTitleBuilder.of(content.text())
               .type(TitleType.SUBTITLE)
               .fadeInFor(Duration.ZERO)
               .fadeOutFor(Duration.ZERO)
               .displayFor(Duration.ofMillis(100));

            while (current < Math.min(0.9, 0.225 * streak.getKills())) {
                long now = System.nanoTime();

                if (now - last < 1633333)
                    continue;

                last = now;
                this.sendPacket(killer, titleBuilder.scale(current).build());
                current += 0.01f;
            }

            this.sendPacket(killer,
               titleBuilder.scale(current)
                  .fadeOutFor(Duration.ofMillis(1000L))
                  .displayFor(Duration.ofMillis(streak == Streak.PENTA || streak == Streak.OVER ? 2000L : 1500L))
                  .build());
        }, streaks.getExecutor());`

as you can see, it is using the ApolloAPI to check the Lunar registration and using the old api to send the title packet.

The showcase (sorry for the bad quality, i had it from a stream on the server) https://clips.twitch.tv/BillowingSparklingDiamondPrimeMe-3H3mXcNzwpMVNDse
If you really can reproduce it in a better way i would be so grateful since i'm currently sending like 25 packets per title and it's overwhelming.

**Comment by ItsNature** [comment]
Issue resolved.
