### ISSUE TITLE
Is there some way to make a GET request to the API to find out of a player uses and/or is online on Lunar Client?

### ISSUE THREAD

**Issue by DexrnZacAttack** [LunarClient/Apollo#89]
Wanting to do some stuff in JS and would like to be able to tell if a player is online on Lunar Client.

**Comment by colinmcdonald22** [comment]
> Wanting to do some stuff in JS and would like to be able to tell if a player is online on Lunar Client.

Unfortunately not right now, although some sort of public API _is_ something we're interested in doing. Is there any specific data you're interested in?

**Comment by DexrnZacAttack** [comment]
> > Wanting to do some stuff in JS and would like to be able to tell if a player is online on Lunar Client.
> 
> Unfortunately not right now, although some sort of public API _is_ something we're interested in doing. Is there any specific data you're interested in?

Mainly just seeing if a player is online on Lunar client, but it would be nice if I could see owned cosmetics, and other stuff.
