### ISSUE TITLE
TNT Countdown module breaks vanilla tnt behaviour

### ISSUE THREAD

**Issue by LaserSlime** [LunarClient/Apollo#98]
Normally tnt that gets ignited by other explosions will have a shorter fuse time. However when the tnt countdown module is enabled in this plugin, all tnt will always have the same fuse time: https://github.com/LunarClient/Apollo/blob/b0cf69a1da442e09da5ced73e2955a993d0817dc/bukkit/src/main/java/com/lunarclient/apollo/module/tntcountdown/TntCountdownModuleImpl.java#L115
I was gonna pr a fix for this but I'm honestly not sure how to fix it. My first instinct was to just ignore all tnt that's ignited by other tnt but I'm not sure if thats the intended behaviour.

**Comment by TrentinTheKid** [comment]
Hey @LaserSlime, we've pushed out an update to resolve this issue. It wasn't as straight forward as we'd hope, due to legacy versions. Regardless, this is our solution: https://github.com/LunarClient/Apollo/pull/125
